### ISSUE TITLE
vendor:publish command meet a problem.

### ISSUE THREAD

**Issue by lihe6666** [HanSon/speedy#10]
hello i am meet a problem.

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "hanson/speedy": "^1.0",
        "jenssegers/mongodb": "3.3.*",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0",
        "symfony/thanks": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

composer require hanson/speedy   .OK

developer:activity.***.com developer$ composer require hanson/speedy
Using version ^1.0 for hanson/speedy
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing hanson/speedy (1.0.7): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: jenssegers/mongodb
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Package manifest generated successfully.

add `Hanson\Speedy\SpeedyServiceProvider::class,` to config/app.php .OK

php artisan vendor:publish --provider="Hanson\Speedy\SpeedyServiceProvider" .ERROR

developer:activity.****.com developer$ php artisan vendor:publish --provider="Hanson\Speedy\SpeedyServiceProvider"
Copied Directory [/vendor/hanson/speedy/src/publishable/assets] To [/public]

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Warning:  Uncaught League\Flysystem\Plugin\PluginNotFoundException: Plugin not found for method: read in /usr/local/var/www/activity.jlgoldenbay.com/vendor/league/flysystem/src/Plugin/PluggableTrait.php:49
Stack trace:
#0 /usr/local/var/www/activity.jlgoldenbay.com/vendor/league/flysystem/src/Plugin/PluggableTrait.php(68): League\Flysystem\MountManager->findPlugin('read')
#1 /usr/local/var/www/activity.jlgoldenbay.com/vendor/league/flysystem/src/MountManager.php(295): League\Flysystem\MountManager->invokePlugin('read', Array, Object(League\Flysystem\Filesystem))
#2 /usr/local/var/www/activity.jlgoldenbay.com/vendor/league/flysystem/src/MountManager.php(188): League\Flysystem\MountManager->invokePluginOnFilesystem('read', Array, 'from')
#3 /usr/local/var/www/activity.jlgoldenbay.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(241): League\Flysystem\MountManager->__call('read', Array)
#4 /usr/local/var/www/activity.jlgoldenbay.com/vendor/laravel/framework/src/Illuminate/Foundation/ in /usr/local/var/www/activity.jlgoldenbay.com/vendor/league/flysystem/src/Plugin/PluggableTrait.php on line 49

**Comment by lihe6666** [comment]
OK. problem resolve. close XDEBUG extension.
